# Generated by Django 6.0.4 on 2026-05-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='phone',
        ),
        migrations.AddField(
            model_name='userregister',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
